version: '1'
services:
  cloud-config:
    image: registry.heroku.com/geek-spring-cloud-config/web:latest
    ports:
      - 8888

  admin_eshop:
    image: registry.heroku.com/geek-admin_eshop/web:latest
    ports:
      - 8080
    volumes:
      - ./storage:/var/storage
    environment:
      - PROFILE=dock
      - CONFIG_SERVER_URL=http://cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh postgresql 5432 && /apps/wait-for-service.sh cloud-config 8888 && /apps/entrypoint.sh"
    restart: always
    depends_on:
      - postgres
      - redis
      - cloud-config

  backend_eshop_user:
    image: registry.heroku.com/geek-backend_eshop_user/web:latest
    ports:
      - 8085:8080
    environment:
      - PROFILE=dock
      - CONFIG_SERVER_URL=http://cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh rabbitmq 5672 && /apps/wait-for-service.sh postgresql 5432 && /apps/wait-for-service.sh cloud-config 8888 && /apps/entrypoint.sh"
    restart: always
    depends_on:
      - postgres
      - redis
      - cloud-config
      - shop-delivery-service
      - rabbitmq
  backend_eshop_company:
    image: registry.heroku.com/geek-backend_eshop_company/web:latest
    ports:
      - 8085:8080
    environment:
      - PROFILE=dock
      - CONFIG_SERVER_URL=http://cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh postgresql 5432 && /apps/wait-for-service.sh cloud-config 8888 && /apps/entrypoint.sh"
    restart: always
    depends_on:
      - postgres
      - redis
      - cloud-config
      - shop-delivery-service
      - rabbitmq

  picture-service-app:
    image: registry.heroku.com/geek-shop-picture-service-api/web:latest
    ports:
      - 8080
    volumes:
      - ./storage:/var/storage
    environment:
      - PROFILE=dock
      - CONFIG_SERVER_URL=http://cloud-config:8888
    command: bash -c "/apps/wait-for-service.sh postgresql 5432 && /apps/wait-for-service.sh cloud-config 8888 && /apps/entrypoint.sh"
    restart: always
    depends_on:
      - postgres
      - cloud-config

  shop-delivery-service:
    image: registry.heroku.com/geek-shop-delivery-service/web:latest
    command: bash -c "/apps/wait-for-service.sh rabbitmq 5672 && /apps/wait-for-service.sh cloud-config 8888 && /apps/entrypoint.sh"
    restart: always
    depends_on:
      - cloud-config
      - rabbitmq

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - 5672
      - 15672:15672

